/**
 * KaTeXが対応するコマンドの一覧（0079）。**手で書き換えない。**
 *
 *   node scripts/extract-katex-commands.mjs
 *
 * で作り直す。例（引数の要るもの）は scripts/guide-examples.mjs にある。
 * 全件がKaTeXで描画できることを生成時に確かめてある（通らないものは落とす）。
 */

/** 第2部の分類。表はこの順で並ぶ。 */
export type GuideCategory =
  | 'relation'
  | 'symbol'
  | 'binary'
  | 'letter'
  | 'operator'
  | 'arrow'
  | 'accent'
  | 'font'
  | 'bracket'
  | 'fraction'
  | 'enclose'
  | 'spacing'
  | 'macro'

export type GuideCommand = {
  /** 書くコマンド。 */
  name: string
  /** 表に描くLaTeX。引数の要るものは例になっている。 */
  latex: string
  category: GuideCategory
  /** ブロック数式でしか描けないもの（\tag）。 */
  displayMode?: true
}

export type GuideEnvironment = { name: string; latex: string }

export const guideCommands: GuideCommand[] = [
  { name: "\\ ", latex: "\\ ", category: "spacing" },
  { name: "\\!", latex: "\\!", category: "macro" },
  { name: "\\#", latex: "\\#", category: "symbol" },
  { name: "\\$", latex: "\\$", category: "symbol" },
  { name: "\\%", latex: "\\%", category: "symbol" },
  { name: "\\&", latex: "\\&", category: "symbol" },
  { name: "\\'", latex: "\\text{\\'e}", category: "accent" },
  { name: "\\(", latex: "\\text{(}", category: "macro" },
  { name: "\\)", latex: "\\text{)}", category: "macro" },
  { name: "\\,", latex: "\\,", category: "macro" },
  { name: "\\.", latex: "\\text{\\.{x}}", category: "accent" },
  { name: "\\:", latex: "\\:", category: "macro" },
  { name: "\\;", latex: "\\;", category: "macro" },
  { name: "\\=", latex: "\\text{\\=e}", category: "accent" },
  { name: "\\>", latex: "\\>", category: "macro" },
  { name: "\\AA", latex: "\\AA", category: "macro" },
  { name: "\\AE", latex: "\\text{\\AE}", category: "symbol" },
  { name: "\\Alpha", latex: "\\Alpha", category: "macro" },
  { name: "\\And", latex: "\\And", category: "binary" },
  { name: "\\Bbb", latex: "\\Bbb{R}", category: "font" },
  { name: "\\Bbbk", latex: "\\Bbbk", category: "macro" },
  { name: "\\Beta", latex: "\\Beta", category: "macro" },
  { name: "\\Big", latex: "\\Big( x \\Big)", category: "bracket" },
  { name: "\\Bigg", latex: "\\Bigg( x \\Bigg)", category: "bracket" },
  { name: "\\Biggl", latex: "\\Biggl( x \\Biggr)", category: "bracket" },
  { name: "\\Biggm", latex: "\\Biggl\\{ x \\Biggm| y \\Biggr\\}", category: "bracket" },
  { name: "\\Biggr", latex: "\\Biggl( x \\Biggr)", category: "bracket" },
  { name: "\\Bigl", latex: "\\Bigl( x \\Bigr)", category: "bracket" },
  { name: "\\Bigm", latex: "\\Bigl\\{ x \\Bigm| y \\Bigr\\}", category: "bracket" },
  { name: "\\Bigr", latex: "\\Bigl( x \\Bigr)", category: "bracket" },
  { name: "\\Box", latex: "\\Box", category: "symbol" },
  { name: "\\Bra", latex: "\\Bra{\\psi}", category: "macro" },
  { name: "\\Braket", latex: "\\Braket{\\phi|\\psi}", category: "macro" },
  { name: "\\Bumpeq", latex: "\\Bumpeq", category: "relation" },
  { name: "\\Cap", latex: "\\Cap", category: "binary" },
  { name: "\\Chi", latex: "\\Chi", category: "macro" },
  { name: "\\Colonapprox", latex: "\\Colonapprox", category: "macro" },
  { name: "\\Coloneq", latex: "\\Coloneq", category: "macro" },
  { name: "\\Coloneqq", latex: "\\Coloneqq", category: "macro" },
  { name: "\\Colonsim", latex: "\\Colonsim", category: "macro" },
  { name: "\\Complex", latex: "\\Complex", category: "macro" },
  { name: "\\Cup", latex: "\\Cup", category: "binary" },
  { name: "\\DOTSB", latex: "\\DOTSB", category: "macro" },
  { name: "\\DOTSI", latex: "\\DOTSI", category: "macro" },
  { name: "\\DOTSX", latex: "\\DOTSX", category: "macro" },
  { name: "\\Dagger", latex: "\\Dagger", category: "macro" },
  { name: "\\Darr", latex: "\\Darr", category: "macro" },
  { name: "\\Delta", latex: "\\Delta", category: "symbol" },
  { name: "\\Diamond", latex: "\\Diamond", category: "symbol" },
  { name: "\\Doteq", latex: "\\Doteq", category: "relation" },
  { name: "\\Downarrow", latex: "\\Downarrow", category: "relation" },
  { name: "\\Epsilon", latex: "\\Epsilon", category: "macro" },
  { name: "\\Eqcolon", latex: "\\Eqcolon", category: "macro" },
  { name: "\\Eqqcolon", latex: "\\Eqqcolon", category: "macro" },
  { name: "\\Eta", latex: "\\Eta", category: "macro" },
  { name: "\\Finv", latex: "\\Finv", category: "symbol" },
  { name: "\\Game", latex: "\\Game", category: "symbol" },
  { name: "\\Gamma", latex: "\\Gamma", category: "symbol" },
  { name: "\\H", latex: "\\text{\\H{o}}", category: "accent" },
  { name: "\\Harr", latex: "\\Harr", category: "macro" },
  { name: "\\Im", latex: "\\Im", category: "symbol" },
  { name: "\\Iota", latex: "\\Iota", category: "macro" },
  { name: "\\Join", latex: "\\Join", category: "relation" },
  { name: "\\KaTeX", latex: "\\KaTeX", category: "macro" },
  { name: "\\Kappa", latex: "\\Kappa", category: "macro" },
  { name: "\\Ket", latex: "\\Ket{\\psi}", category: "macro" },
  { name: "\\LaTeX", latex: "\\LaTeX", category: "macro" },
  { name: "\\Lambda", latex: "\\Lambda", category: "symbol" },
  { name: "\\Larr", latex: "\\Larr", category: "macro" },
  { name: "\\Leftarrow", latex: "\\Leftarrow", category: "relation" },
  { name: "\\Leftrightarrow", latex: "\\Leftrightarrow", category: "relation" },
  { name: "\\Lleftarrow", latex: "\\Lleftarrow", category: "relation" },
  { name: "\\Longleftarrow", latex: "\\Longleftarrow", category: "relation" },
  { name: "\\Longleftrightarrow", latex: "\\Longleftrightarrow", category: "relation" },
  { name: "\\Longrightarrow", latex: "\\Longrightarrow", category: "relation" },
  { name: "\\Lrarr", latex: "\\Lrarr", category: "macro" },
  { name: "\\Lsh", latex: "\\Lsh", category: "relation" },
  { name: "\\Mu", latex: "\\Mu", category: "macro" },
  { name: "\\N", latex: "\\N", category: "macro" },
  { name: "\\Nu", latex: "\\Nu", category: "macro" },
  { name: "\\O", latex: "\\text{\\O}", category: "symbol" },
  { name: "\\OE", latex: "\\text{\\OE}", category: "symbol" },
  { name: "\\Omega", latex: "\\Omega", category: "symbol" },
  { name: "\\Omicron", latex: "\\Omicron", category: "macro" },
  { name: "\\Overrightarrow", latex: "\\Overrightarrow{AB}", category: "accent" },
  { name: "\\P", latex: "\\P", category: "symbol" },
  { name: "\\Phi", latex: "\\Phi", category: "symbol" },
  { name: "\\Pi", latex: "\\Pi", category: "symbol" },
  { name: "\\Pr", latex: "\\Pr", category: "operator" },
  { name: "\\Psi", latex: "\\Psi", category: "symbol" },
  { name: "\\R", latex: "\\R", category: "macro" },
  { name: "\\Rarr", latex: "\\Rarr", category: "macro" },
  { name: "\\Re", latex: "\\Re", category: "symbol" },
  { name: "\\Reals", latex: "\\Reals", category: "macro" },
  { name: "\\Rho", latex: "\\Rho", category: "macro" },
  { name: "\\Rightarrow", latex: "\\Rightarrow", category: "relation" },
  { name: "\\Rrightarrow", latex: "\\Rrightarrow", category: "relation" },
  { name: "\\Rsh", latex: "\\Rsh", category: "relation" },
  { name: "\\S", latex: "\\S", category: "symbol" },
  { name: "\\Set", latex: "\\Set{x | x > 0}", category: "macro" },
  { name: "\\Sigma", latex: "\\Sigma", category: "symbol" },
  { name: "\\Subset", latex: "\\Subset", category: "relation" },
  { name: "\\Supset", latex: "\\Supset", category: "relation" },
  { name: "\\Tau", latex: "\\Tau", category: "macro" },
  { name: "\\TeX", latex: "\\TeX", category: "macro" },
  { name: "\\TextOrMath", latex: "\\TextOrMath{text}{math}", category: "macro" },
  { name: "\\Theta", latex: "\\Theta", category: "symbol" },
  { name: "\\Uarr", latex: "\\Uarr", category: "macro" },
  { name: "\\Uparrow", latex: "\\Uparrow", category: "relation" },
  { name: "\\Updownarrow", latex: "\\Updownarrow", category: "relation" },
  { name: "\\Upsilon", latex: "\\Upsilon", category: "symbol" },
  { name: "\\Vdash", latex: "\\Vdash", category: "relation" },
  { name: "\\Vert", latex: "\\Vert", category: "symbol" },
  { name: "\\Vvdash", latex: "\\Vvdash", category: "relation" },
  { name: "\\Xi", latex: "\\Xi", category: "symbol" },
  { name: "\\Z", latex: "\\Z", category: "macro" },
  { name: "\\Zeta", latex: "\\Zeta", category: "macro" },
  { name: "\\\\", latex: "\\\\", category: "spacing" },
  { name: "\\^", latex: "\\text{\\^e}", category: "accent" },
  { name: "\\_", latex: "\\_", category: "symbol" },
  { name: "\\`", latex: "\\text{\\`e}", category: "accent" },
  { name: "\\aa", latex: "\\aa", category: "macro" },
  { name: "\\above", latex: "{a \\above 1pt b}", category: "fraction" },
  { name: "\\acute", latex: "\\acute{a}", category: "accent" },
  { name: "\\ae", latex: "\\text{\\ae}", category: "symbol" },
  { name: "\\alef", latex: "\\alef", category: "macro" },
  { name: "\\alefsym", latex: "\\alefsym", category: "macro" },
  { name: "\\aleph", latex: "\\aleph", category: "symbol" },
  { name: "\\allowbreak", latex: "\\allowbreak", category: "spacing" },
  { name: "\\alpha", latex: "\\alpha", category: "letter" },
  { name: "\\amalg", latex: "\\amalg", category: "binary" },
  { name: "\\angl", latex: "\\angl{x}", category: "enclose" },
  { name: "\\angle", latex: "\\angle", category: "symbol" },
  { name: "\\angln", latex: "\\angln", category: "macro" },
  { name: "\\approx", latex: "\\approx", category: "relation" },
  { name: "\\approxcolon", latex: "\\approxcolon", category: "macro" },
  { name: "\\approxcoloncolon", latex: "\\approxcoloncolon", category: "macro" },
  { name: "\\approxeq", latex: "\\approxeq", category: "relation" },
  { name: "\\arccos", latex: "\\arccos", category: "operator" },
  { name: "\\arcctg", latex: "\\arcctg", category: "operator" },
  { name: "\\arcsin", latex: "\\arcsin", category: "operator" },
  { name: "\\arctan", latex: "\\arctan", category: "operator" },
  { name: "\\arctg", latex: "\\arctg", category: "operator" },
  { name: "\\arg", latex: "\\arg", category: "operator" },
  { name: "\\argmax", latex: "\\argmax", category: "macro" },
  { name: "\\argmin", latex: "\\argmin", category: "macro" },
  { name: "\\ast", latex: "\\ast", category: "binary" },
  { name: "\\asymp", latex: "\\asymp", category: "relation" },
  { name: "\\atop", latex: "{a \\atop b}", category: "fraction" },
  { name: "\\backepsilon", latex: "\\backepsilon", category: "relation" },
  { name: "\\backprime", latex: "\\backprime", category: "symbol" },
  { name: "\\backsim", latex: "\\backsim", category: "relation" },
  { name: "\\backsimeq", latex: "\\backsimeq", category: "relation" },
  { name: "\\backslash", latex: "\\backslash", category: "symbol" },
  { name: "\\bar", latex: "\\bar{x}", category: "accent" },
  { name: "\\barwedge", latex: "\\barwedge", category: "binary" },
  { name: "\\bcancel", latex: "\\bcancel{x}", category: "enclose" },
  { name: "\\because", latex: "\\because", category: "relation" },
  { name: "\\begin", latex: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}", category: "macro" },
  { name: "\\beta", latex: "\\beta", category: "letter" },
  { name: "\\beth", latex: "\\beth", category: "symbol" },
  { name: "\\between", latex: "\\between", category: "relation" },
  { name: "\\bf", latex: "\\bf", category: "font" },
  { name: "\\bgroup", latex: "\\bgroup x \\egroup", category: "macro" },
  { name: "\\big", latex: "\\big( x \\big)", category: "bracket" },
  { name: "\\bigcap", latex: "\\bigcap", category: "operator" },
  { name: "\\bigcirc", latex: "\\bigcirc", category: "binary" },
  { name: "\\bigcup", latex: "\\bigcup", category: "operator" },
  { name: "\\bigg", latex: "\\bigg( x \\bigg)", category: "bracket" },
  { name: "\\biggl", latex: "\\biggl( x \\biggr)", category: "bracket" },
  { name: "\\biggm", latex: "\\biggl\\{ x \\biggm| y \\biggr\\}", category: "bracket" },
  { name: "\\biggr", latex: "\\biggl( x \\biggr)", category: "bracket" },
  { name: "\\bigl", latex: "\\bigl( x \\bigr)", category: "bracket" },
  { name: "\\bigm", latex: "\\bigl\\{ x \\bigm| y \\bigr\\}", category: "bracket" },
  { name: "\\bigodot", latex: "\\bigodot", category: "operator" },
  { name: "\\bigoplus", latex: "\\bigoplus", category: "operator" },
  { name: "\\bigotimes", latex: "\\bigotimes", category: "operator" },
  { name: "\\bigr", latex: "\\bigl( x \\bigr)", category: "bracket" },
  { name: "\\bigsqcup", latex: "\\bigsqcup", category: "operator" },
  { name: "\\bigstar", latex: "\\bigstar", category: "symbol" },
  { name: "\\bigtriangledown", latex: "\\bigtriangledown", category: "binary" },
  { name: "\\bigtriangleup", latex: "\\bigtriangleup", category: "binary" },
  { name: "\\biguplus", latex: "\\biguplus", category: "operator" },
  { name: "\\bigvee", latex: "\\bigvee", category: "operator" },
  { name: "\\bigwedge", latex: "\\bigwedge", category: "operator" },
  { name: "\\binom", latex: "\\binom{n}{k}", category: "fraction" },
  { name: "\\blacklozenge", latex: "\\blacklozenge", category: "symbol" },
  { name: "\\blacksquare", latex: "\\blacksquare", category: "symbol" },
  { name: "\\blacktriangle", latex: "\\blacktriangle", category: "symbol" },
  { name: "\\blacktriangledown", latex: "\\blacktriangledown", category: "symbol" },
  { name: "\\blacktriangleleft", latex: "\\blacktriangleleft", category: "relation" },
  { name: "\\blacktriangleright", latex: "\\blacktriangleright", category: "relation" },
  { name: "\\bm", latex: "\\bm{v}", category: "font" },
  { name: "\\bmod", latex: "\\bmod", category: "macro" },
  { name: "\\bold", latex: "\\bold{A}", category: "font" },
  { name: "\\boldsymbol", latex: "\\boldsymbol{\\alpha}", category: "font" },
  { name: "\\bot", latex: "\\bot", category: "symbol" },
  { name: "\\bowtie", latex: "\\bowtie", category: "relation" },
  { name: "\\boxdot", latex: "\\boxdot", category: "binary" },
  { name: "\\boxed", latex: "\\boxed{x + y}", category: "macro" },
  { name: "\\boxminus", latex: "\\boxminus", category: "binary" },
  { name: "\\boxplus", latex: "\\boxplus", category: "binary" },
  { name: "\\boxtimes", latex: "\\boxtimes", category: "binary" },
  { name: "\\bra", latex: "\\bra{\\psi}", category: "macro" },
  { name: "\\brace", latex: "{n \\brace k}", category: "fraction" },
  { name: "\\brack", latex: "{n \\brack k}", category: "fraction" },
  { name: "\\braket", latex: "\\braket{\\phi|\\psi}", category: "macro" },
  { name: "\\breve", latex: "\\breve{a}", category: "accent" },
  { name: "\\bull", latex: "\\bull", category: "macro" },
  { name: "\\bullet", latex: "\\bullet", category: "binary" },
  { name: "\\bumpeq", latex: "\\bumpeq", category: "relation" },
  { name: "\\c", latex: "\\text{\\c{c}}", category: "accent" },
  { name: "\\cal", latex: "\\cal", category: "font" },
  { name: "\\cancel", latex: "\\cancel{x}", category: "enclose" },
  { name: "\\cap", latex: "\\cap", category: "binary" },
  { name: "\\cdot", latex: "\\cdot", category: "binary" },
  { name: "\\cdotp", latex: "\\cdotp", category: "symbol" },
  { name: "\\cdots", latex: "\\cdots", category: "macro" },
  { name: "\\centerdot", latex: "\\centerdot", category: "binary" },
  { name: "\\cfrac", latex: "\\cfrac{1}{1 + \\cfrac{1}{x}}", category: "fraction" },
  { name: "\\ch", latex: "\\ch", category: "operator" },
  { name: "\\char", latex: "\\char\"41", category: "macro" },
  { name: "\\check", latex: "\\check{a}", category: "accent" },
  { name: "\\checkmark", latex: "\\checkmark", category: "symbol" },
  { name: "\\chi", latex: "\\chi", category: "letter" },
  { name: "\\choose", latex: "{n \\choose k}", category: "fraction" },
  { name: "\\circ", latex: "\\circ", category: "binary" },
  { name: "\\circeq", latex: "\\circeq", category: "relation" },
  { name: "\\circlearrowleft", latex: "\\circlearrowleft", category: "relation" },
  { name: "\\circlearrowright", latex: "\\circlearrowright", category: "relation" },
  { name: "\\circledR", latex: "\\circledR", category: "symbol" },
  { name: "\\circledS", latex: "\\circledS", category: "symbol" },
  { name: "\\circledast", latex: "\\circledast", category: "binary" },
  { name: "\\circledcirc", latex: "\\circledcirc", category: "binary" },
  { name: "\\circleddash", latex: "\\circleddash", category: "binary" },
  { name: "\\clap", latex: "\\clap{x}", category: "macro" },
  { name: "\\clubs", latex: "\\clubs", category: "macro" },
  { name: "\\clubsuit", latex: "\\clubsuit", category: "symbol" },
  { name: "\\cnums", latex: "\\cnums", category: "macro" },
  { name: "\\colon", latex: "\\colon", category: "macro" },
  { name: "\\colonapprox", latex: "\\colonapprox", category: "macro" },
  { name: "\\coloncolon", latex: "\\coloncolon", category: "macro" },
  { name: "\\coloncolonapprox", latex: "\\coloncolonapprox", category: "macro" },
  { name: "\\coloncolonequals", latex: "\\coloncolonequals", category: "macro" },
  { name: "\\coloncolonminus", latex: "\\coloncolonminus", category: "macro" },
  { name: "\\coloncolonsim", latex: "\\coloncolonsim", category: "macro" },
  { name: "\\coloneq", latex: "\\coloneq", category: "macro" },
  { name: "\\coloneqq", latex: "\\coloneqq", category: "macro" },
  { name: "\\colonequals", latex: "\\colonequals", category: "macro" },
  { name: "\\colonminus", latex: "\\colonminus", category: "macro" },
  { name: "\\colonsim", latex: "\\colonsim", category: "macro" },
  { name: "\\color", latex: "{\\color{red} x}", category: "macro" },
  { name: "\\colorbox", latex: "\\colorbox{yellow}{x}", category: "enclose" },
  { name: "\\complement", latex: "\\complement", category: "symbol" },
  { name: "\\cong", latex: "\\cong", category: "relation" },
  { name: "\\coprod", latex: "\\coprod", category: "operator" },
  { name: "\\copyright", latex: "\\copyright", category: "macro" },
  { name: "\\cos", latex: "\\cos", category: "operator" },
  { name: "\\cosec", latex: "\\cosec", category: "operator" },
  { name: "\\cosh", latex: "\\cosh", category: "operator" },
  { name: "\\cot", latex: "\\cot", category: "operator" },
  { name: "\\cotg", latex: "\\cotg", category: "operator" },
  { name: "\\coth", latex: "\\coth", category: "operator" },
  { name: "\\csc", latex: "\\csc", category: "operator" },
  { name: "\\ctg", latex: "\\ctg", category: "operator" },
  { name: "\\cth", latex: "\\cth", category: "operator" },
  { name: "\\cup", latex: "\\cup", category: "binary" },
  { name: "\\curlyeqprec", latex: "\\curlyeqprec", category: "relation" },
  { name: "\\curlyeqsucc", latex: "\\curlyeqsucc", category: "relation" },
  { name: "\\curlyvee", latex: "\\curlyvee", category: "binary" },
  { name: "\\curlywedge", latex: "\\curlywedge", category: "binary" },
  { name: "\\curvearrowleft", latex: "\\curvearrowleft", category: "relation" },
  { name: "\\curvearrowright", latex: "\\curvearrowright", category: "relation" },
  { name: "\\dArr", latex: "\\dArr", category: "macro" },
  { name: "\\dag", latex: "\\dag", category: "symbol" },
  { name: "\\dagger", latex: "\\dagger", category: "binary" },
  { name: "\\daleth", latex: "\\daleth", category: "symbol" },
  { name: "\\darr", latex: "\\darr", category: "macro" },
  { name: "\\dashleftarrow", latex: "\\dashleftarrow", category: "relation" },
  { name: "\\dashrightarrow", latex: "\\dashrightarrow", category: "relation" },
  { name: "\\dashv", latex: "\\dashv", category: "relation" },
  { name: "\\dbinom", latex: "\\dbinom{n}{k}", category: "fraction" },
  { name: "\\dblcolon", latex: "\\dblcolon", category: "macro" },
  { name: "\\ddag", latex: "\\ddag", category: "symbol" },
  { name: "\\ddagger", latex: "\\ddagger", category: "binary" },
  { name: "\\ddddot", latex: "\\ddddot{x}", category: "macro" },
  { name: "\\dddot", latex: "\\dddot{x}", category: "macro" },
  { name: "\\ddot", latex: "\\ddot{x}", category: "accent" },
  { name: "\\ddots", latex: "\\ddots", category: "symbol" },
  { name: "\\def", latex: "\\def\\myR{\\mathbb{R}} \\myR", category: "macro" },
  { name: "\\deg", latex: "\\deg", category: "operator" },
  { name: "\\degree", latex: "\\degree", category: "symbol" },
  { name: "\\delta", latex: "\\delta", category: "letter" },
  { name: "\\det", latex: "\\det", category: "operator" },
  { name: "\\dfrac", latex: "\\dfrac{a}{b}", category: "fraction" },
  { name: "\\diagdown", latex: "\\diagdown", category: "symbol" },
  { name: "\\diagup", latex: "\\diagup", category: "symbol" },
  { name: "\\diamond", latex: "\\diamond", category: "binary" },
  { name: "\\diamonds", latex: "\\diamonds", category: "macro" },
  { name: "\\diamondsuit", latex: "\\diamondsuit", category: "symbol" },
  { name: "\\digamma", latex: "\\digamma", category: "symbol" },
  { name: "\\dim", latex: "\\dim", category: "operator" },
  { name: "\\displaystyle", latex: "\\displaystyle", category: "font" },
  { name: "\\div", latex: "\\div", category: "binary" },
  { name: "\\divideontimes", latex: "\\divideontimes", category: "binary" },
  { name: "\\dot", latex: "\\dot{x}", category: "accent" },
  { name: "\\doteq", latex: "\\doteq", category: "relation" },
  { name: "\\doteqdot", latex: "\\doteqdot", category: "relation" },
  { name: "\\dotplus", latex: "\\dotplus", category: "binary" },
  { name: "\\dots", latex: "\\dots", category: "macro" },
  { name: "\\dotsb", latex: "\\dotsb", category: "macro" },
  { name: "\\dotsc", latex: "\\dotsc", category: "macro" },
  { name: "\\dotsi", latex: "\\dotsi", category: "macro" },
  { name: "\\dotsm", latex: "\\dotsm", category: "macro" },
  { name: "\\dotso", latex: "\\dotso", category: "macro" },
  { name: "\\dotsx", latex: "\\dotsx", category: "macro" },
  { name: "\\doublebarwedge", latex: "\\doublebarwedge", category: "binary" },
  { name: "\\doublecap", latex: "\\doublecap", category: "binary" },
  { name: "\\doublecup", latex: "\\doublecup", category: "binary" },
  { name: "\\downarrow", latex: "\\downarrow", category: "relation" },
  { name: "\\downdownarrows", latex: "\\downdownarrows", category: "relation" },
  { name: "\\downharpoonleft", latex: "\\downharpoonleft", category: "relation" },
  { name: "\\downharpoonright", latex: "\\downharpoonright", category: "relation" },
  { name: "\\edef", latex: "\\edef\\myR{\\mathbb{R}} \\myR", category: "macro" },
  { name: "\\egroup", latex: "\\bgroup x \\egroup", category: "macro" },
  { name: "\\ell", latex: "\\ell", category: "symbol" },
  { name: "\\emph", latex: "\\emph{x}", category: "macro" },
  { name: "\\empty", latex: "\\empty", category: "macro" },
  { name: "\\emptyset", latex: "\\emptyset", category: "symbol" },
  { name: "\\end", latex: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}", category: "macro" },
  { name: "\\enskip", latex: "\\enskip", category: "macro" },
  { name: "\\enspace", latex: "\\enspace", category: "macro" },
  { name: "\\epsilon", latex: "\\epsilon", category: "letter" },
  { name: "\\eqcirc", latex: "\\eqcirc", category: "relation" },
  { name: "\\eqcolon", latex: "\\eqcolon", category: "macro" },
  { name: "\\eqqcolon", latex: "\\eqqcolon", category: "macro" },
  { name: "\\eqsim", latex: "\\eqsim", category: "relation" },
  { name: "\\eqslantgtr", latex: "\\eqslantgtr", category: "relation" },
  { name: "\\eqslantless", latex: "\\eqslantless", category: "relation" },
  { name: "\\equalscolon", latex: "\\equalscolon", category: "macro" },
  { name: "\\equalscoloncolon", latex: "\\equalscoloncolon", category: "macro" },
  { name: "\\equiv", latex: "\\equiv", category: "relation" },
  { name: "\\eta", latex: "\\eta", category: "letter" },
  { name: "\\eth", latex: "\\eth", category: "symbol" },
  { name: "\\exist", latex: "\\exist", category: "macro" },
  { name: "\\exists", latex: "\\exists", category: "symbol" },
  { name: "\\exp", latex: "\\exp", category: "operator" },
  { name: "\\expandafter", latex: "\\expandafter", category: "macro" },
  { name: "\\fallingdotseq", latex: "\\fallingdotseq", category: "relation" },
  { name: "\\fbox", latex: "\\fbox{x}", category: "enclose" },
  { name: "\\fcolorbox", latex: "\\fcolorbox{red}{yellow}{x}", category: "enclose" },
  { name: "\\flat", latex: "\\flat", category: "symbol" },
  { name: "\\forall", latex: "\\forall", category: "symbol" },
  { name: "\\frac", latex: "\\frac{a}{b}", category: "fraction" },
  { name: "\\frak", latex: "\\frak{A}", category: "font" },
  { name: "\\frown", latex: "\\frown", category: "relation" },
  { name: "\\futurelet", latex: "\\futurelet\\next\\relax x", category: "macro" },
  { name: "\\gamma", latex: "\\gamma", category: "letter" },
  { name: "\\gcd", latex: "\\gcd", category: "operator" },
  { name: "\\gdef", latex: "\\gdef\\myR{\\mathbb{R}} \\myR", category: "macro" },
  { name: "\\ge", latex: "\\ge", category: "relation" },
  { name: "\\genfrac", latex: "\\genfrac{(}{)}{0pt}{}{n}{k}", category: "fraction" },
  { name: "\\geq", latex: "\\geq", category: "relation" },
  { name: "\\geqq", latex: "\\geqq", category: "relation" },
  { name: "\\geqslant", latex: "\\geqslant", category: "relation" },
  { name: "\\gets", latex: "\\gets", category: "relation" },
  { name: "\\gg", latex: "\\gg", category: "relation" },
  { name: "\\ggg", latex: "\\ggg", category: "relation" },
  { name: "\\gggtr", latex: "\\gggtr", category: "relation" },
  { name: "\\gimel", latex: "\\gimel", category: "symbol" },
  { name: "\\global", latex: "\\global\\def\\myR{\\mathbb{R}} \\myR", category: "macro" },
  { name: "\\gnapprox", latex: "\\gnapprox", category: "relation" },
  { name: "\\gneq", latex: "\\gneq", category: "relation" },
  { name: "\\gneqq", latex: "\\gneqq", category: "relation" },
  { name: "\\gnsim", latex: "\\gnsim", category: "relation" },
  { name: "\\grave", latex: "\\grave{a}", category: "accent" },
  { name: "\\gt", latex: "\\gt", category: "relation" },
  { name: "\\gtrapprox", latex: "\\gtrapprox", category: "relation" },
  { name: "\\gtrdot", latex: "\\gtrdot", category: "binary" },
  { name: "\\gtreqless", latex: "\\gtreqless", category: "relation" },
  { name: "\\gtreqqless", latex: "\\gtreqqless", category: "relation" },
  { name: "\\gtrless", latex: "\\gtrless", category: "relation" },
  { name: "\\gtrsim", latex: "\\gtrsim", category: "relation" },
  { name: "\\gvertneqq", latex: "\\gvertneqq", category: "macro" },
  { name: "\\hArr", latex: "\\hArr", category: "macro" },
  { name: "\\harr", latex: "\\harr", category: "macro" },
  { name: "\\hat", latex: "\\hat{a}", category: "accent" },
  { name: "\\hbar", latex: "\\hbar", category: "symbol" },
  { name: "\\hbox", latex: "\\hbox{x}", category: "macro" },
  { name: "\\hearts", latex: "\\hearts", category: "macro" },
  { name: "\\heartsuit", latex: "\\heartsuit", category: "symbol" },
  { name: "\\hom", latex: "\\hom", category: "operator" },
  { name: "\\hookleftarrow", latex: "\\hookleftarrow", category: "relation" },
  { name: "\\hookrightarrow", latex: "\\hookrightarrow", category: "relation" },
  { name: "\\href", latex: "\\href{https://katex.org}{KaTeX}", category: "macro" },
  { name: "\\hskip", latex: "a \\hskip 1em b", category: "spacing" },
  { name: "\\hslash", latex: "\\hslash", category: "symbol" },
  { name: "\\hspace", latex: "a \\hspace{1em} b", category: "macro" },
  { name: "\\htmlClass", latex: "\\htmlClass{note}{x}", category: "macro" },
  { name: "\\htmlData", latex: "\\htmlData{k=v}{x}", category: "macro" },
  { name: "\\htmlId", latex: "\\htmlId{eq1}{x}", category: "macro" },
  { name: "\\htmlStyle", latex: "\\htmlStyle{color: red}{x}", category: "macro" },
  { name: "\\i", latex: "\\text{\\i}", category: "symbol" },
  { name: "\\iff", latex: "\\iff", category: "macro" },
  { name: "\\iiint", latex: "\\iiint", category: "operator" },
  { name: "\\iint", latex: "\\iint", category: "operator" },
  { name: "\\image", latex: "\\image", category: "macro" },
  { name: "\\imageof", latex: "\\imageof", category: "relation" },
  { name: "\\imath", latex: "\\imath", category: "macro" },
  { name: "\\impliedby", latex: "\\impliedby", category: "macro" },
  { name: "\\implies", latex: "\\implies", category: "macro" },
  { name: "\\in", latex: "\\in", category: "relation" },
  { name: "\\includegraphics", latex: "\\includegraphics[height=1em]{https://katex.org/img/khan-academy.png}", category: "macro" },
  { name: "\\inf", latex: "\\inf", category: "operator" },
  { name: "\\infin", latex: "\\infin", category: "macro" },
  { name: "\\infty", latex: "\\infty", category: "symbol" },
  { name: "\\injlim", latex: "\\injlim", category: "macro" },
  { name: "\\int", latex: "\\int", category: "operator" },
  { name: "\\intercal", latex: "\\intercal", category: "binary" },
  { name: "\\intop", latex: "\\intop", category: "operator" },
  { name: "\\iota", latex: "\\iota", category: "letter" },
  { name: "\\isin", latex: "\\isin", category: "macro" },
  { name: "\\it", latex: "\\it", category: "font" },
  { name: "\\j", latex: "\\text{\\j}", category: "symbol" },
  { name: "\\jmath", latex: "\\jmath", category: "macro" },
  { name: "\\kappa", latex: "\\kappa", category: "letter" },
  { name: "\\ker", latex: "\\ker", category: "operator" },
  { name: "\\kern", latex: "a \\kern 1em b", category: "spacing" },
  { name: "\\ket", latex: "\\ket{\\psi}", category: "macro" },
  { name: "\\lArr", latex: "\\lArr", category: "macro" },
  { name: "\\lBrace", latex: "\\lBrace", category: "macro" },
  { name: "\\lVert", latex: "\\lVert", category: "bracket" },
  { name: "\\lambda", latex: "\\lambda", category: "letter" },
  { name: "\\land", latex: "\\land", category: "binary" },
  { name: "\\lang", latex: "\\lang", category: "macro" },
  { name: "\\langle", latex: "\\langle", category: "bracket" },
  { name: "\\larr", latex: "\\larr", category: "macro" },
  { name: "\\lbrace", latex: "\\lbrace", category: "bracket" },
  { name: "\\lbrack", latex: "\\lbrack", category: "bracket" },
  { name: "\\lceil", latex: "\\lceil", category: "bracket" },
  { name: "\\ldotp", latex: "\\ldotp", category: "symbol" },
  { name: "\\ldots", latex: "\\ldots", category: "symbol" },
  { name: "\\le", latex: "\\le", category: "relation" },
  { name: "\\leadsto", latex: "\\leadsto", category: "relation" },
  { name: "\\left", latex: "\\left( \\frac{a}{b} \\right)", category: "bracket" },
  { name: "\\leftarrow", latex: "\\leftarrow", category: "relation" },
  { name: "\\leftarrowtail", latex: "\\leftarrowtail", category: "relation" },
  { name: "\\leftharpoondown", latex: "\\leftharpoondown", category: "relation" },
  { name: "\\leftharpoonup", latex: "\\leftharpoonup", category: "relation" },
  { name: "\\leftleftarrows", latex: "\\leftleftarrows", category: "relation" },
  { name: "\\leftrightarrow", latex: "\\leftrightarrow", category: "relation" },
  { name: "\\leftrightarrows", latex: "\\leftrightarrows", category: "relation" },
  { name: "\\leftrightharpoons", latex: "\\leftrightharpoons", category: "relation" },
  { name: "\\leftrightsquigarrow", latex: "\\leftrightsquigarrow", category: "relation" },
  { name: "\\leftthreetimes", latex: "\\leftthreetimes", category: "binary" },
  { name: "\\leq", latex: "\\leq", category: "relation" },
  { name: "\\leqq", latex: "\\leqq", category: "relation" },
  { name: "\\leqslant", latex: "\\leqslant", category: "relation" },
  { name: "\\lessapprox", latex: "\\lessapprox", category: "relation" },
  { name: "\\lessdot", latex: "\\lessdot", category: "binary" },
  { name: "\\lesseqgtr", latex: "\\lesseqgtr", category: "relation" },
  { name: "\\lesseqqgtr", latex: "\\lesseqqgtr", category: "relation" },
  { name: "\\lessgtr", latex: "\\lessgtr", category: "relation" },
  { name: "\\lesssim", latex: "\\lesssim", category: "relation" },
  { name: "\\let", latex: "\\let\\a=\\alpha \\a", category: "macro" },
  { name: "\\lfloor", latex: "\\lfloor", category: "bracket" },
  { name: "\\lg", latex: "\\lg", category: "operator" },
  { name: "\\lgroup", latex: "\\lgroup", category: "bracket" },
  { name: "\\lhd", latex: "\\lhd", category: "binary" },
  { name: "\\lim", latex: "\\lim", category: "operator" },
  { name: "\\liminf", latex: "\\liminf", category: "macro" },
  { name: "\\limsup", latex: "\\limsup", category: "macro" },
  { name: "\\ll", latex: "\\ll", category: "relation" },
  { name: "\\llap", latex: "\\llap{x}", category: "macro" },
  { name: "\\llbracket", latex: "\\llbracket", category: "macro" },
  { name: "\\llcorner", latex: "\\llcorner", category: "macro" },
  { name: "\\lll", latex: "\\lll", category: "relation" },
  { name: "\\llless", latex: "\\llless", category: "relation" },
  { name: "\\lmoustache", latex: "\\lmoustache", category: "bracket" },
  { name: "\\ln", latex: "\\ln", category: "operator" },
  { name: "\\lnapprox", latex: "\\lnapprox", category: "relation" },
  { name: "\\lneq", latex: "\\lneq", category: "relation" },
  { name: "\\lneqq", latex: "\\lneqq", category: "relation" },
  { name: "\\lnot", latex: "\\lnot", category: "symbol" },
  { name: "\\lnsim", latex: "\\lnsim", category: "relation" },
  { name: "\\log", latex: "\\log", category: "operator" },
  { name: "\\long", latex: "\\long\\def\\myR{\\mathbb{R}} \\myR", category: "macro" },
  { name: "\\longleftarrow", latex: "\\longleftarrow", category: "relation" },
  { name: "\\longleftrightarrow", latex: "\\longleftrightarrow", category: "relation" },
  { name: "\\longmapsto", latex: "\\longmapsto", category: "relation" },
  { name: "\\longrightarrow", latex: "\\longrightarrow", category: "relation" },
  { name: "\\looparrowleft", latex: "\\looparrowleft", category: "relation" },
  { name: "\\looparrowright", latex: "\\looparrowright", category: "relation" },
  { name: "\\lor", latex: "\\lor", category: "binary" },
  { name: "\\lozenge", latex: "\\lozenge", category: "symbol" },
  { name: "\\lparen", latex: "\\lparen", category: "bracket" },
  { name: "\\lq", latex: "\\lq", category: "macro" },
  { name: "\\lrArr", latex: "\\lrArr", category: "macro" },
  { name: "\\lrarr", latex: "\\lrarr", category: "macro" },
  { name: "\\lrcorner", latex: "\\lrcorner", category: "macro" },
  { name: "\\lt", latex: "\\lt", category: "relation" },
  { name: "\\ltimes", latex: "\\ltimes", category: "binary" },
  { name: "\\lvert", latex: "\\lvert", category: "bracket" },
  { name: "\\lvertneqq", latex: "\\lvertneqq", category: "macro" },
  { name: "\\maltese", latex: "\\maltese", category: "symbol" },
  { name: "\\mapsfrom", latex: "\\mapsfrom", category: "macro" },
  { name: "\\mapsto", latex: "\\mapsto", category: "relation" },
  { name: "\\mathbb", latex: "\\mathbb{R}", category: "font" },
  { name: "\\mathbf", latex: "\\mathbf{A}", category: "font" },
  { name: "\\mathbin", latex: "a \\mathbin{\\star} b", category: "macro" },
  { name: "\\mathcal", latex: "\\mathcal{L}", category: "font" },
  { name: "\\mathchoice", latex: "\\mathchoice{D}{T}{S}{SS}", category: "macro" },
  { name: "\\mathclap", latex: "\\mathclap{x}", category: "macro" },
  { name: "\\mathclose", latex: "\\mathclose{)}", category: "macro" },
  { name: "\\mathellipsis", latex: "\\mathellipsis", category: "symbol" },
  { name: "\\mathfrak", latex: "\\mathfrak{g}", category: "font" },
  { name: "\\mathinner", latex: "\\mathinner{\\ldots}", category: "macro" },
  { name: "\\mathit", latex: "\\mathit{x}", category: "font" },
  { name: "\\mathllap", latex: "\\mathllap{x}", category: "macro" },
  { name: "\\mathnormal", latex: "\\mathnormal{x}", category: "font" },
  { name: "\\mathop", latex: "\\mathop{\\mathrm{tr}} A", category: "operator" },
  { name: "\\mathopen", latex: "\\mathopen{(}", category: "macro" },
  { name: "\\mathord", latex: "\\mathord{+}", category: "macro" },
  { name: "\\mathpunct", latex: "\\mathpunct{,}", category: "macro" },
  { name: "\\mathreflectbox", latex: "\\mathreflectbox{abc}", category: "macro" },
  { name: "\\mathrel", latex: "a \\mathrel{\\#} b", category: "macro" },
  { name: "\\mathring", latex: "\\mathring{a}", category: "accent" },
  { name: "\\mathrlap", latex: "\\mathrlap{x}", category: "macro" },
  { name: "\\mathrm", latex: "\\mathrm{d}x", category: "font" },
  { name: "\\mathscr", latex: "\\mathscr{F}", category: "font" },
  { name: "\\mathsf", latex: "\\mathsf{A}", category: "font" },
  { name: "\\mathsfit", latex: "\\mathsfit{A}", category: "font" },
  { name: "\\mathsterling", latex: "\\mathsterling", category: "symbol" },
  { name: "\\mathstrut", latex: "\\mathstrut", category: "macro" },
  { name: "\\mathtt", latex: "\\mathtt{A}", category: "font" },
  { name: "\\max", latex: "\\max", category: "operator" },
  { name: "\\measuredangle", latex: "\\measuredangle", category: "symbol" },
  { name: "\\medspace", latex: "\\medspace", category: "macro" },
  { name: "\\mho", latex: "\\mho", category: "symbol" },
  { name: "\\mid", latex: "\\mid", category: "relation" },
  { name: "\\middle", latex: "\\left( x \\middle| y \\right)", category: "bracket" },
  { name: "\\min", latex: "\\min", category: "operator" },
  { name: "\\minuscolon", latex: "\\minuscolon", category: "macro" },
  { name: "\\minuscoloncolon", latex: "\\minuscoloncolon", category: "macro" },
  { name: "\\minuso", latex: "\\minuso", category: "macro" },
  { name: "\\mkern", latex: "a \\mkern 18mu b", category: "spacing" },
  { name: "\\mod", latex: "a \\mod b", category: "macro" },
  { name: "\\models", latex: "\\models", category: "relation" },
  { name: "\\mp", latex: "\\mp", category: "binary" },
  { name: "\\mskip", latex: "a \\mskip 18mu b", category: "spacing" },
  { name: "\\mu", latex: "\\mu", category: "letter" },
  { name: "\\multimap", latex: "\\multimap", category: "relation" },
  { name: "\\nLeftarrow", latex: "\\nLeftarrow", category: "relation" },
  { name: "\\nLeftrightarrow", latex: "\\nLeftrightarrow", category: "relation" },
  { name: "\\nRightarrow", latex: "\\nRightarrow", category: "relation" },
  { name: "\\nVDash", latex: "\\nVDash", category: "relation" },
  { name: "\\nVdash", latex: "\\nVdash", category: "relation" },
  { name: "\\nabla", latex: "\\nabla", category: "symbol" },
  { name: "\\natnums", latex: "\\natnums", category: "macro" },
  { name: "\\natural", latex: "\\natural", category: "symbol" },
  { name: "\\ncong", latex: "\\ncong", category: "relation" },
  { name: "\\ne", latex: "\\ne", category: "macro" },
  { name: "\\nearrow", latex: "\\nearrow", category: "relation" },
  { name: "\\neg", latex: "\\neg", category: "symbol" },
  { name: "\\negmedspace", latex: "\\negmedspace", category: "macro" },
  { name: "\\negthickspace", latex: "\\negthickspace", category: "macro" },
  { name: "\\negthinspace", latex: "\\negthinspace", category: "macro" },
  { name: "\\neq", latex: "\\neq", category: "macro" },
  { name: "\\newcommand", latex: "\\newcommand{\\myR}{\\mathbb{R}} \\myR", category: "macro" },
  { name: "\\newline", latex: "\\newline", category: "macro" },
  { name: "\\nexists", latex: "\\nexists", category: "symbol" },
  { name: "\\ngeq", latex: "\\ngeq", category: "relation" },
  { name: "\\ngeqq", latex: "\\ngeqq", category: "macro" },
  { name: "\\ngeqslant", latex: "\\ngeqslant", category: "macro" },
  { name: "\\ngtr", latex: "\\ngtr", category: "relation" },
  { name: "\\ni", latex: "\\ni", category: "relation" },
  { name: "\\nleftarrow", latex: "\\nleftarrow", category: "relation" },
  { name: "\\nleftrightarrow", latex: "\\nleftrightarrow", category: "relation" },
  { name: "\\nleq", latex: "\\nleq", category: "relation" },
  { name: "\\nleqq", latex: "\\nleqq", category: "macro" },
  { name: "\\nleqslant", latex: "\\nleqslant", category: "macro" },
  { name: "\\nless", latex: "\\nless", category: "relation" },
  { name: "\\nmid", latex: "\\nmid", category: "relation" },
  { name: "\\nobreak", latex: "\\nobreak", category: "spacing" },
  { name: "\\nobreakspace", latex: "\\nobreakspace", category: "spacing" },
  { name: "\\noexpand", latex: "\\noexpand", category: "macro" },
  { name: "\\not", latex: "\\not", category: "macro" },
  { name: "\\notin", latex: "\\notin", category: "macro" },
  { name: "\\notni", latex: "\\notni", category: "macro" },
  { name: "\\nparallel", latex: "\\nparallel", category: "relation" },
  { name: "\\nprec", latex: "\\nprec", category: "relation" },
  { name: "\\npreceq", latex: "\\npreceq", category: "relation" },
  { name: "\\nrightarrow", latex: "\\nrightarrow", category: "relation" },
  { name: "\\nshortmid", latex: "\\nshortmid", category: "macro" },
  { name: "\\nshortparallel", latex: "\\nshortparallel", category: "macro" },
  { name: "\\nsim", latex: "\\nsim", category: "relation" },
  { name: "\\nsubseteq", latex: "\\nsubseteq", category: "relation" },
  { name: "\\nsubseteqq", latex: "\\nsubseteqq", category: "macro" },
  { name: "\\nsucc", latex: "\\nsucc", category: "relation" },
  { name: "\\nsucceq", latex: "\\nsucceq", category: "relation" },
  { name: "\\nsupseteq", latex: "\\nsupseteq", category: "relation" },
  { name: "\\nsupseteqq", latex: "\\nsupseteqq", category: "macro" },
  { name: "\\ntriangleleft", latex: "\\ntriangleleft", category: "relation" },
  { name: "\\ntrianglelefteq", latex: "\\ntrianglelefteq", category: "relation" },
  { name: "\\ntriangleright", latex: "\\ntriangleright", category: "relation" },
  { name: "\\ntrianglerighteq", latex: "\\ntrianglerighteq", category: "relation" },
  { name: "\\nu", latex: "\\nu", category: "letter" },
  { name: "\\nvDash", latex: "\\nvDash", category: "relation" },
  { name: "\\nvdash", latex: "\\nvdash", category: "relation" },
  { name: "\\nwarrow", latex: "\\nwarrow", category: "relation" },
  { name: "\\o", latex: "\\text{\\o}", category: "symbol" },
  { name: "\\odot", latex: "\\odot", category: "binary" },
  { name: "\\oe", latex: "\\text{\\oe}", category: "symbol" },
  { name: "\\oiiint", latex: "\\oiiint", category: "operator" },
  { name: "\\oiint", latex: "\\oiint", category: "operator" },
  { name: "\\oint", latex: "\\oint", category: "operator" },
  { name: "\\omega", latex: "\\omega", category: "letter" },
  { name: "\\omicron", latex: "\\omicron", category: "letter" },
  { name: "\\ominus", latex: "\\ominus", category: "binary" },
  { name: "\\operatornamewithlimits", latex: "\\operatornamewithlimits{argmax}_{x} f(x)", category: "macro" },
  { name: "\\oplus", latex: "\\oplus", category: "binary" },
  { name: "\\orange", latex: "\\orange{x}", category: "macro" },
  { name: "\\ordinarycolon", latex: "\\ordinarycolon", category: "macro" },
  { name: "\\origof", latex: "\\origof", category: "relation" },
  { name: "\\oslash", latex: "\\oslash", category: "binary" },
  { name: "\\otimes", latex: "\\otimes", category: "binary" },
  { name: "\\over", latex: "{a \\over b}", category: "fraction" },
  { name: "\\overbrace", latex: "\\overbrace{a + b}^{n}", category: "enclose" },
  { name: "\\overbracket", latex: "\\overbracket{a + b}", category: "enclose" },
  { name: "\\overgroup", latex: "\\overgroup{AB}", category: "accent" },
  { name: "\\overleftarrow", latex: "\\overleftarrow{AB}", category: "accent" },
  { name: "\\overleftharpoon", latex: "\\overleftharpoon{AB}", category: "accent" },
  { name: "\\overleftrightarrow", latex: "\\overleftrightarrow{AB}", category: "accent" },
  { name: "\\overline", latex: "\\overline{AB}", category: "enclose" },
  { name: "\\overlinesegment", latex: "\\overlinesegment{AB}", category: "accent" },
  { name: "\\overrightarrow", latex: "\\overrightarrow{AB}", category: "accent" },
  { name: "\\overrightharpoon", latex: "\\overrightharpoon{AB}", category: "accent" },
  { name: "\\overset", latex: "\\overset{!}{=}", category: "macro" },
  { name: "\\owns", latex: "\\owns", category: "relation" },
  { name: "\\parallel", latex: "\\parallel", category: "relation" },
  { name: "\\partial", latex: "\\partial", category: "symbol" },
  { name: "\\perp", latex: "\\perp", category: "relation" },
  { name: "\\phantom", latex: "a \\phantom{b} c", category: "macro" },
  { name: "\\phase", latex: "\\phase{30^\\circ}", category: "enclose" },
  { name: "\\phi", latex: "\\phi", category: "letter" },
  { name: "\\pi", latex: "\\pi", category: "letter" },
  { name: "\\pitchfork", latex: "\\pitchfork", category: "relation" },
  { name: "\\plim", latex: "\\plim", category: "macro" },
  { name: "\\plusmn", latex: "\\plusmn", category: "macro" },
  { name: "\\pm", latex: "\\pm", category: "binary" },
  { name: "\\pmb", latex: "\\pmb{\\mu}", category: "macro" },
  { name: "\\pmod", latex: "a \\equiv b \\pmod{n}", category: "macro" },
  { name: "\\pod", latex: "a \\equiv b \\pod{n}", category: "macro" },
  { name: "\\pounds", latex: "\\pounds", category: "symbol" },
  { name: "\\prec", latex: "\\prec", category: "relation" },
  { name: "\\precapprox", latex: "\\precapprox", category: "relation" },
  { name: "\\preccurlyeq", latex: "\\preccurlyeq", category: "relation" },
  { name: "\\preceq", latex: "\\preceq", category: "relation" },
  { name: "\\precnapprox", latex: "\\precnapprox", category: "relation" },
  { name: "\\precneqq", latex: "\\precneqq", category: "relation" },
  { name: "\\precnsim", latex: "\\precnsim", category: "relation" },
  { name: "\\precsim", latex: "\\precsim", category: "relation" },
  { name: "\\prime", latex: "\\prime", category: "symbol" },
  { name: "\\prod", latex: "\\prod", category: "operator" },
  { name: "\\projlim", latex: "\\projlim", category: "macro" },
  { name: "\\propto", latex: "\\propto", category: "relation" },
  { name: "\\providecommand", latex: "\\providecommand{\\myR}{\\mathbb{R}} \\myR", category: "macro" },
  { name: "\\psi", latex: "\\psi", category: "letter" },
  { name: "\\qquad", latex: "\\qquad", category: "macro" },
  { name: "\\quad", latex: "\\quad", category: "macro" },
  { name: "\\r", latex: "\\text{\\r{a}}", category: "accent" },
  { name: "\\rArr", latex: "\\rArr", category: "macro" },
  { name: "\\rBrace", latex: "\\rBrace", category: "macro" },
  { name: "\\rVert", latex: "\\rVert", category: "bracket" },
  { name: "\\raisebox", latex: "\\raisebox{0.5em}{x}", category: "macro" },
  { name: "\\rang", latex: "\\rang", category: "macro" },
  { name: "\\rangle", latex: "\\rangle", category: "bracket" },
  { name: "\\rarr", latex: "\\rarr", category: "macro" },
  { name: "\\ratio", latex: "\\ratio", category: "macro" },
  { name: "\\rbrace", latex: "\\rbrace", category: "bracket" },
  { name: "\\rbrack", latex: "\\rbrack", category: "bracket" },
  { name: "\\rceil", latex: "\\rceil", category: "bracket" },
  { name: "\\real", latex: "\\real", category: "macro" },
  { name: "\\reals", latex: "\\reals", category: "macro" },
  { name: "\\reflectbox", latex: "\\reflectbox{abc}", category: "macro" },
  { name: "\\relax", latex: "\\relax", category: "macro" },
  { name: "\\renewcommand", latex: "\\renewcommand{\\vec}{\\mathbf} \\vec{v}", category: "macro" },
  { name: "\\restriction", latex: "\\restriction", category: "relation" },
  { name: "\\rfloor", latex: "\\rfloor", category: "bracket" },
  { name: "\\rgroup", latex: "\\rgroup", category: "bracket" },
  { name: "\\rhd", latex: "\\rhd", category: "binary" },
  { name: "\\rho", latex: "\\rho", category: "letter" },
  { name: "\\right", latex: "\\left( \\frac{a}{b} \\right)", category: "bracket" },
  { name: "\\rightarrow", latex: "\\rightarrow", category: "relation" },
  { name: "\\rightarrowtail", latex: "\\rightarrowtail", category: "relation" },
  { name: "\\rightharpoondown", latex: "\\rightharpoondown", category: "relation" },
  { name: "\\rightharpoonup", latex: "\\rightharpoonup", category: "relation" },
  { name: "\\rightleftarrows", latex: "\\rightleftarrows", category: "relation" },
  { name: "\\rightleftharpoons", latex: "\\rightleftharpoons", category: "relation" },
  { name: "\\rightrightarrows", latex: "\\rightrightarrows", category: "relation" },
  { name: "\\rightsquigarrow", latex: "\\rightsquigarrow", category: "relation" },
  { name: "\\rightthreetimes", latex: "\\rightthreetimes", category: "binary" },
  { name: "\\risingdotseq", latex: "\\risingdotseq", category: "relation" },
  { name: "\\rlap", latex: "\\rlap{x}", category: "macro" },
  { name: "\\rm", latex: "\\rm", category: "font" },
  { name: "\\rmoustache", latex: "\\rmoustache", category: "bracket" },
  { name: "\\rparen", latex: "\\rparen", category: "bracket" },
  { name: "\\rq", latex: "\\rq", category: "macro" },
  { name: "\\rrbracket", latex: "\\rrbracket", category: "macro" },
  { name: "\\rtimes", latex: "\\rtimes", category: "binary" },
  { name: "\\rule", latex: "\\rule{1em}{0.5em}", category: "macro" },
  { name: "\\rvert", latex: "\\rvert", category: "bracket" },
  { name: "\\scriptscriptstyle", latex: "\\scriptscriptstyle", category: "font" },
  { name: "\\scriptstyle", latex: "\\scriptstyle", category: "font" },
  { name: "\\sdot", latex: "\\sdot", category: "macro" },
  { name: "\\searrow", latex: "\\searrow", category: "relation" },
  { name: "\\sec", latex: "\\sec", category: "operator" },
  { name: "\\sect", latex: "\\sect", category: "macro" },
  { name: "\\set", latex: "\\set{x | x > 0}", category: "macro" },
  { name: "\\setminus", latex: "\\setminus", category: "binary" },
  { name: "\\sf", latex: "\\sf", category: "font" },
  { name: "\\sh", latex: "\\sh", category: "operator" },
  { name: "\\sharp", latex: "\\sharp", category: "symbol" },
  { name: "\\shortmid", latex: "\\shortmid", category: "relation" },
  { name: "\\shortparallel", latex: "\\shortparallel", category: "relation" },
  { name: "\\sigma", latex: "\\sigma", category: "letter" },
  { name: "\\sim", latex: "\\sim", category: "relation" },
  { name: "\\simcolon", latex: "\\simcolon", category: "macro" },
  { name: "\\simcoloncolon", latex: "\\simcoloncolon", category: "macro" },
  { name: "\\simeq", latex: "\\simeq", category: "relation" },
  { name: "\\sin", latex: "\\sin", category: "operator" },
  { name: "\\sinh", latex: "\\sinh", category: "operator" },
  { name: "\\smallfrown", latex: "\\smallfrown", category: "relation" },
  { name: "\\smallint", latex: "\\smallint", category: "operator" },
  { name: "\\smallsetminus", latex: "\\smallsetminus", category: "binary" },
  { name: "\\smallsmile", latex: "\\smallsmile", category: "relation" },
  { name: "\\smash", latex: "\\smash{\\frac{a}{b}}", category: "macro" },
  { name: "\\smile", latex: "\\smile", category: "relation" },
  { name: "\\sout", latex: "\\sout{x}", category: "enclose" },
  { name: "\\space", latex: "\\space", category: "spacing" },
  { name: "\\spades", latex: "\\spades", category: "macro" },
  { name: "\\spadesuit", latex: "\\spadesuit", category: "symbol" },
  { name: "\\sphericalangle", latex: "\\sphericalangle", category: "symbol" },
  { name: "\\sqcap", latex: "\\sqcap", category: "binary" },
  { name: "\\sqcup", latex: "\\sqcup", category: "binary" },
  { name: "\\sqrt", latex: "\\sqrt{x}", category: "macro" },
  { name: "\\sqsubset", latex: "\\sqsubset", category: "relation" },
  { name: "\\sqsubseteq", latex: "\\sqsubseteq", category: "relation" },
  { name: "\\sqsupset", latex: "\\sqsupset", category: "relation" },
  { name: "\\sqsupseteq", latex: "\\sqsupseteq", category: "relation" },
  { name: "\\square", latex: "\\square", category: "symbol" },
  { name: "\\ss", latex: "\\text{\\ss}", category: "symbol" },
  { name: "\\stackrel", latex: "\\stackrel{f}{\\to}", category: "macro" },
  { name: "\\star", latex: "\\star", category: "binary" },
  { name: "\\sub", latex: "\\sub", category: "macro" },
  { name: "\\sube", latex: "\\sube", category: "macro" },
  { name: "\\subset", latex: "\\subset", category: "relation" },
  { name: "\\subseteq", latex: "\\subseteq", category: "relation" },
  { name: "\\subseteqq", latex: "\\subseteqq", category: "relation" },
  { name: "\\subsetneq", latex: "\\subsetneq", category: "relation" },
  { name: "\\subsetneqq", latex: "\\subsetneqq", category: "relation" },
  { name: "\\substack", latex: "\\sum_{\\substack{0 < i < n \\\\ 0 < j < n}} a_{ij}", category: "macro" },
  { name: "\\succ", latex: "\\succ", category: "relation" },
  { name: "\\succapprox", latex: "\\succapprox", category: "relation" },
  { name: "\\succcurlyeq", latex: "\\succcurlyeq", category: "relation" },
  { name: "\\succeq", latex: "\\succeq", category: "relation" },
  { name: "\\succnapprox", latex: "\\succnapprox", category: "relation" },
  { name: "\\succneqq", latex: "\\succneqq", category: "relation" },
  { name: "\\succnsim", latex: "\\succnsim", category: "relation" },
  { name: "\\succsim", latex: "\\succsim", category: "relation" },
  { name: "\\sum", latex: "\\sum", category: "operator" },
  { name: "\\sup", latex: "\\sup", category: "operator" },
  { name: "\\supe", latex: "\\supe", category: "macro" },
  { name: "\\supset", latex: "\\supset", category: "relation" },
  { name: "\\supseteq", latex: "\\supseteq", category: "relation" },
  { name: "\\supseteqq", latex: "\\supseteqq", category: "relation" },
  { name: "\\supsetneq", latex: "\\supsetneq", category: "relation" },
  { name: "\\supsetneqq", latex: "\\supsetneqq", category: "relation" },
  { name: "\\surd", latex: "\\surd", category: "symbol" },
  { name: "\\swarrow", latex: "\\swarrow", category: "relation" },
  { name: "\\tag", latex: "x + y = z \\tag{1}", category: "macro", displayMode: true },
  { name: "\\tan", latex: "\\tan", category: "operator" },
  { name: "\\tanh", latex: "\\tanh", category: "operator" },
  { name: "\\tau", latex: "\\tau", category: "letter" },
  { name: "\\tbinom", latex: "\\tbinom{n}{k}", category: "fraction" },
  { name: "\\text", latex: "\\text{ここは文章}", category: "macro" },
  { name: "\\textasciicircum", latex: "\\text{\\textasciicircum}", category: "symbol" },
  { name: "\\textasciitilde", latex: "\\text{\\textasciitilde}", category: "symbol" },
  { name: "\\textbackslash", latex: "\\text{\\textbackslash}", category: "symbol" },
  { name: "\\textbar", latex: "\\text{\\textbar}", category: "symbol" },
  { name: "\\textbardbl", latex: "\\text{\\textbardbl}", category: "symbol" },
  { name: "\\textbf", latex: "\\textbf{bold}", category: "macro" },
  { name: "\\textbraceleft", latex: "\\text{\\textbraceleft}", category: "symbol" },
  { name: "\\textbraceright", latex: "\\text{\\textbraceright}", category: "symbol" },
  { name: "\\textcircled", latex: "\\text{\\textcircled{a}}", category: "accent" },
  { name: "\\textcolor", latex: "\\textcolor{red}{x}", category: "macro" },
  { name: "\\textcopyright", latex: "\\textcopyright", category: "macro" },
  { name: "\\textdagger", latex: "\\text{\\textdagger}", category: "symbol" },
  { name: "\\textdaggerdbl", latex: "\\text{\\textdaggerdbl}", category: "symbol" },
  { name: "\\textdegree", latex: "\\text{\\textdegree}", category: "symbol" },
  { name: "\\textdollar", latex: "\\text{\\textdollar}", category: "symbol" },
  { name: "\\textellipsis", latex: "\\text{\\textellipsis}", category: "symbol" },
  { name: "\\textemdash", latex: "\\text{\\textemdash}", category: "symbol" },
  { name: "\\textendash", latex: "\\text{\\textendash}", category: "symbol" },
  { name: "\\textgreater", latex: "\\text{\\textgreater}", category: "symbol" },
  { name: "\\textit", latex: "\\textit{italic}", category: "macro" },
  { name: "\\textless", latex: "\\text{\\textless}", category: "symbol" },
  { name: "\\textmd", latex: "\\textmd{medium}", category: "macro" },
  { name: "\\textnormal", latex: "\\textnormal{normal}", category: "macro" },
  { name: "\\textquotedblleft", latex: "\\text{\\textquotedblleft}", category: "symbol" },
  { name: "\\textquotedblright", latex: "\\text{\\textquotedblright}", category: "symbol" },
  { name: "\\textquoteleft", latex: "\\text{\\textquoteleft}", category: "symbol" },
  { name: "\\textquoteright", latex: "\\text{\\textquoteright}", category: "symbol" },
  { name: "\\textregistered", latex: "\\textregistered", category: "macro" },
  { name: "\\textrm", latex: "\\textrm{roman}", category: "macro" },
  { name: "\\textsf", latex: "\\textsf{sans}", category: "macro" },
  { name: "\\textsterling", latex: "\\text{\\textsterling}", category: "symbol" },
  { name: "\\textstyle", latex: "\\textstyle", category: "font" },
  { name: "\\texttt", latex: "\\texttt{mono}", category: "macro" },
  { name: "\\textunderscore", latex: "\\text{\\textunderscore}", category: "symbol" },
  { name: "\\textup", latex: "\\textup{upright}", category: "macro" },
  { name: "\\tfrac", latex: "\\tfrac{a}{b}", category: "fraction" },
  { name: "\\tg", latex: "\\tg", category: "operator" },
  { name: "\\th", latex: "\\th", category: "operator" },
  { name: "\\therefore", latex: "\\therefore", category: "relation" },
  { name: "\\theta", latex: "\\theta", category: "letter" },
  { name: "\\thetasym", latex: "\\thetasym", category: "macro" },
  { name: "\\thickapprox", latex: "\\thickapprox", category: "relation" },
  { name: "\\thicksim", latex: "\\thicksim", category: "relation" },
  { name: "\\thickspace", latex: "\\thickspace", category: "macro" },
  { name: "\\thinspace", latex: "\\thinspace", category: "macro" },
  { name: "\\tilde", latex: "\\tilde{a}", category: "accent" },
  { name: "\\times", latex: "\\times", category: "binary" },
  { name: "\\tmspace", latex: "a \\tmspace+{2mu} b", category: "macro" },
  { name: "\\to", latex: "\\to", category: "relation" },
  { name: "\\top", latex: "\\top", category: "symbol" },
  { name: "\\triangle", latex: "\\triangle", category: "symbol" },
  { name: "\\triangledown", latex: "\\triangledown", category: "symbol" },
  { name: "\\triangleleft", latex: "\\triangleleft", category: "binary" },
  { name: "\\trianglelefteq", latex: "\\trianglelefteq", category: "relation" },
  { name: "\\triangleq", latex: "\\triangleq", category: "relation" },
  { name: "\\triangleright", latex: "\\triangleright", category: "binary" },
  { name: "\\trianglerighteq", latex: "\\trianglerighteq", category: "relation" },
  { name: "\\tt", latex: "\\tt", category: "font" },
  { name: "\\twoheadleftarrow", latex: "\\twoheadleftarrow", category: "relation" },
  { name: "\\twoheadrightarrow", latex: "\\twoheadrightarrow", category: "relation" },
  { name: "\\u", latex: "\\text{\\u{a}}", category: "accent" },
  { name: "\\uArr", latex: "\\uArr", category: "macro" },
  { name: "\\uarr", latex: "\\uarr", category: "macro" },
  { name: "\\ulcorner", latex: "\\ulcorner", category: "macro" },
  { name: "\\underbar", latex: "\\underbar{x}", category: "macro" },
  { name: "\\underbrace", latex: "\\underbrace{a + b}_{n}", category: "enclose" },
  { name: "\\underbracket", latex: "\\underbracket{a + b}", category: "enclose" },
  { name: "\\undergroup", latex: "\\undergroup{AB}", category: "accent" },
  { name: "\\underleftarrow", latex: "\\underleftarrow{AB}", category: "accent" },
  { name: "\\underleftrightarrow", latex: "\\underleftrightarrow{AB}", category: "accent" },
  { name: "\\underline", latex: "\\underline{AB}", category: "enclose" },
  { name: "\\underlinesegment", latex: "\\underlinesegment{AB}", category: "accent" },
  { name: "\\underrightarrow", latex: "\\underrightarrow{AB}", category: "accent" },
  { name: "\\underset", latex: "\\underset{n}{\\lim}", category: "macro" },
  { name: "\\unlhd", latex: "\\unlhd", category: "binary" },
  { name: "\\unrhd", latex: "\\unrhd", category: "binary" },
  { name: "\\uparrow", latex: "\\uparrow", category: "relation" },
  { name: "\\updownarrow", latex: "\\updownarrow", category: "relation" },
  { name: "\\upharpoonleft", latex: "\\upharpoonleft", category: "relation" },
  { name: "\\upharpoonright", latex: "\\upharpoonright", category: "relation" },
  { name: "\\uplus", latex: "\\uplus", category: "binary" },
  { name: "\\upsilon", latex: "\\upsilon", category: "letter" },
  { name: "\\upuparrows", latex: "\\upuparrows", category: "relation" },
  { name: "\\urcorner", latex: "\\urcorner", category: "macro" },
  { name: "\\url", latex: "\\url{https://katex.org}", category: "macro" },
  { name: "\\utilde", latex: "\\utilde{abc}", category: "accent" },
  { name: "\\v", latex: "\\text{\\v{s}}", category: "accent" },
  { name: "\\vDash", latex: "\\vDash", category: "relation" },
  { name: "\\varDelta", latex: "\\varDelta", category: "macro" },
  { name: "\\varGamma", latex: "\\varGamma", category: "macro" },
  { name: "\\varLambda", latex: "\\varLambda", category: "macro" },
  { name: "\\varOmega", latex: "\\varOmega", category: "macro" },
  { name: "\\varPhi", latex: "\\varPhi", category: "macro" },
  { name: "\\varPi", latex: "\\varPi", category: "macro" },
  { name: "\\varPsi", latex: "\\varPsi", category: "macro" },
  { name: "\\varSigma", latex: "\\varSigma", category: "macro" },
  { name: "\\varTheta", latex: "\\varTheta", category: "macro" },
  { name: "\\varUpsilon", latex: "\\varUpsilon", category: "macro" },
  { name: "\\varXi", latex: "\\varXi", category: "macro" },
  { name: "\\varepsilon", latex: "\\varepsilon", category: "letter" },
  { name: "\\varinjlim", latex: "\\varinjlim", category: "macro" },
  { name: "\\varkappa", latex: "\\varkappa", category: "symbol" },
  { name: "\\varliminf", latex: "\\varliminf", category: "macro" },
  { name: "\\varlimsup", latex: "\\varlimsup", category: "macro" },
  { name: "\\varnothing", latex: "\\varnothing", category: "symbol" },
  { name: "\\varphi", latex: "\\varphi", category: "letter" },
  { name: "\\varpi", latex: "\\varpi", category: "letter" },
  { name: "\\varprojlim", latex: "\\varprojlim", category: "macro" },
  { name: "\\varpropto", latex: "\\varpropto", category: "relation" },
  { name: "\\varrho", latex: "\\varrho", category: "letter" },
  { name: "\\varsigma", latex: "\\varsigma", category: "letter" },
  { name: "\\varsubsetneq", latex: "\\varsubsetneq", category: "macro" },
  { name: "\\varsubsetneqq", latex: "\\varsubsetneqq", category: "macro" },
  { name: "\\varsupsetneq", latex: "\\varsupsetneq", category: "macro" },
  { name: "\\varsupsetneqq", latex: "\\varsupsetneqq", category: "macro" },
  { name: "\\vartheta", latex: "\\vartheta", category: "letter" },
  { name: "\\vartriangle", latex: "\\vartriangle", category: "relation" },
  { name: "\\vartriangleleft", latex: "\\vartriangleleft", category: "relation" },
  { name: "\\vartriangleright", latex: "\\vartriangleright", category: "relation" },
  { name: "\\varvdots", latex: "\\varvdots", category: "symbol" },
  { name: "\\vcentcolon", latex: "\\vcentcolon", category: "macro" },
  { name: "\\vcenter", latex: "\\vcenter{\\hbox{x}}", category: "macro" },
  { name: "\\vdash", latex: "\\vdash", category: "relation" },
  { name: "\\vdots", latex: "\\vdots", category: "macro" },
  { name: "\\vec", latex: "\\vec{v}", category: "accent" },
  { name: "\\vee", latex: "\\vee", category: "binary" },
  { name: "\\veebar", latex: "\\veebar", category: "binary" },
  { name: "\\verb", latex: "\\verb|x + y|", category: "macro" },
  { name: "\\vert", latex: "\\vert", category: "symbol" },
  { name: "\\vphantom", latex: "a \\vphantom{\\frac{1}{2}} c", category: "macro" },
  { name: "\\wedge", latex: "\\wedge", category: "binary" },
  { name: "\\weierp", latex: "\\weierp", category: "macro" },
  { name: "\\widecheck", latex: "\\widecheck{abc}", category: "accent" },
  { name: "\\widehat", latex: "\\widehat{abc}", category: "accent" },
  { name: "\\widetilde", latex: "\\widetilde{abc}", category: "accent" },
  { name: "\\wp", latex: "\\wp", category: "symbol" },
  { name: "\\wr", latex: "\\wr", category: "binary" },
  { name: "\\xLeftarrow", latex: "\\xLeftarrow{f}", category: "arrow" },
  { name: "\\xLeftrightarrow", latex: "\\xLeftrightarrow{f}", category: "arrow" },
  { name: "\\xRightarrow", latex: "\\xRightarrow{f}", category: "arrow" },
  { name: "\\xcancel", latex: "\\xcancel{x}", category: "enclose" },
  { name: "\\xdef", latex: "\\xdef\\myR{\\mathbb{R}} \\myR", category: "macro" },
  { name: "\\xhookleftarrow", latex: "\\xhookleftarrow{f}", category: "arrow" },
  { name: "\\xhookrightarrow", latex: "\\xhookrightarrow{f}", category: "arrow" },
  { name: "\\xi", latex: "\\xi", category: "letter" },
  { name: "\\xleftarrow", latex: "\\xleftarrow{f}", category: "arrow" },
  { name: "\\xleftequilibrium", latex: "\\xleftequilibrium{f}", category: "arrow" },
  { name: "\\xleftharpoondown", latex: "\\xleftharpoondown{f}", category: "arrow" },
  { name: "\\xleftharpoonup", latex: "\\xleftharpoonup{f}", category: "arrow" },
  { name: "\\xleftrightarrow", latex: "\\xleftrightarrow{f}", category: "arrow" },
  { name: "\\xleftrightharpoons", latex: "\\xleftrightharpoons{f}", category: "arrow" },
  { name: "\\xlongequal", latex: "\\xlongequal{f}", category: "arrow" },
  { name: "\\xmapsto", latex: "\\xmapsto{f}", category: "arrow" },
  { name: "\\xrightarrow", latex: "\\xrightarrow{f}", category: "arrow" },
  { name: "\\xrightequilibrium", latex: "\\xrightequilibrium{f}", category: "arrow" },
  { name: "\\xrightharpoondown", latex: "\\xrightharpoondown{f}", category: "arrow" },
  { name: "\\xrightharpoonup", latex: "\\xrightharpoonup{f}", category: "arrow" },
  { name: "\\xrightleftarrows", latex: "\\xrightleftarrows{f}", category: "arrow" },
  { name: "\\xrightleftharpoons", latex: "\\xrightleftharpoons{f}", category: "arrow" },
  { name: "\\xtofrom", latex: "\\xtofrom{f}", category: "arrow" },
  { name: "\\xtwoheadleftarrow", latex: "\\xtwoheadleftarrow{f}", category: "arrow" },
  { name: "\\xtwoheadrightarrow", latex: "\\xtwoheadrightarrow{f}", category: "arrow" },
  { name: "\\yen", latex: "\\yen", category: "symbol" },
  { name: "\\zeta", latex: "\\zeta", category: "letter" },
  { name: "\\{", latex: "\\{", category: "bracket" },
  { name: "\\|", latex: "\\|", category: "symbol" },
  { name: "\\}", latex: "\\}", category: "bracket" },
  { name: "\\~", latex: "\\text{\\~n}", category: "accent" },
]

export const guideEnvironments: GuideEnvironment[] = [
  { name: "Bmatrix", latex: "\\begin{Bmatrix} a & b \\\\ c & d \\end{Bmatrix}" },
  { name: "Bmatrix*", latex: "\\begin{Bmatrix*} a & b \\\\ c & d \\end{Bmatrix*}" },
  { name: "CD", latex: "\\begin{CD} a & b \\\\ c & d \\end{CD}" },
  { name: "Vmatrix", latex: "\\begin{Vmatrix} a & b \\\\ c & d \\end{Vmatrix}" },
  { name: "Vmatrix*", latex: "\\begin{Vmatrix*} a & b \\\\ c & d \\end{Vmatrix*}" },
  { name: "align", latex: "\\begin{align} a & b \\\\ c & d \\end{align}" },
  { name: "align*", latex: "\\begin{align*} a & b \\\\ c & d \\end{align*}" },
  { name: "alignat", latex: "\\begin{alignat}{2} a &= b & \\quad c &= d \\end{alignat}" },
  { name: "alignat*", latex: "\\begin{alignat*}{2} a &= b & \\quad c &= d \\end{alignat*}" },
  { name: "aligned", latex: "\\begin{aligned} a & b \\\\ c & d \\end{aligned}" },
  { name: "alignedat", latex: "\\begin{alignedat}{2} a &= b & \\quad c &= d \\end{alignedat}" },
  { name: "array", latex: "\\begin{array}{cc} a & b \\\\ c & d \\end{array}" },
  { name: "bmatrix", latex: "\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}" },
  { name: "bmatrix*", latex: "\\begin{bmatrix*} a & b \\\\ c & d \\end{bmatrix*}" },
  { name: "cases", latex: "\\begin{cases} a & b \\\\ c & d \\end{cases}" },
  { name: "darray", latex: "\\begin{darray}{cc} a & b \\\\ c & d \\end{darray}" },
  { name: "dcases", latex: "\\begin{dcases} a & b \\\\ c & d \\end{dcases}" },
  { name: "drcases", latex: "\\begin{drcases} a & b \\\\ c & d \\end{drcases}" },
  { name: "equation", latex: "\\begin{equation} a = b \\end{equation}" },
  { name: "equation*", latex: "\\begin{equation*} a = b \\end{equation*}" },
  { name: "gather", latex: "\\begin{gather} a & b \\\\ c & d \\end{gather}" },
  { name: "gather*", latex: "\\begin{gather*} a & b \\\\ c & d \\end{gather*}" },
  { name: "gathered", latex: "\\begin{gathered} a & b \\\\ c & d \\end{gathered}" },
  { name: "matrix", latex: "\\begin{matrix} a & b \\\\ c & d \\end{matrix}" },
  { name: "matrix*", latex: "\\begin{matrix*} a & b \\\\ c & d \\end{matrix*}" },
  { name: "pmatrix", latex: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}" },
  { name: "pmatrix*", latex: "\\begin{pmatrix*} a & b \\\\ c & d \\end{pmatrix*}" },
  { name: "rcases", latex: "\\begin{rcases} a & b \\\\ c & d \\end{rcases}" },
  { name: "smallmatrix", latex: "\\begin{smallmatrix} a & b \\\\ c & d \\end{smallmatrix}" },
  { name: "split", latex: "\\begin{split} a & b \\\\ c & d \\end{split}" },
  { name: "subarray", latex: "\\sum_{\\begin{subarray}{c} 0 < i < n \\\\ 0 < j < n \\end{subarray}} a_{ij}" },
  { name: "vmatrix", latex: "\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}" },
  { name: "vmatrix*", latex: "\\begin{vmatrix*} a & b \\\\ c & d \\end{vmatrix*}" },
]
